### ISSUE TITLE
Review API documentation, get successful call with Postman

### ISSUE THREAD

**Issue by Epanastatis2020** [Epanastatis2020/Informed-Travel-App#7]
Get some successful basic calls with Weatherbit API & NewsAPI

**Comment by Epanastatis2020** [comment]
Succesful call to weatherAPI using this query URL:

https://api.weatherbit.io/v2.0/current?city=Sydney&key=[ourAPIkey]

**Comment by amightyrose** [comment]
NewsAPI didn't work so now going with GNews API. Testing now.

**Comment by amightyrose** [comment]
Successfully made requests to GNews API. I believe this issue can be closed now.

**Comment by amightyrose** [comment]
All calls to APIs working.
